version: '3'

services:
  apache_php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8101:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3309:3309"
